name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ðŸ“¦ Install Dependencies
        run: npm ci

      - name: ðŸš€ Run Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
        run: npx --yes semantic-release

      - name: ðŸ“¡ Sync Selectors to Gist
        if: steps.release.outputs.released == 'true'
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET_TOKEN }}
          gist_id: ${{ vars.GIST_ID }}
          gist_file_name: selectors.json
          file_path: src/config/selectors.json

#      - name: ðŸš€ Upload to Chrome Web Store
#        if: steps.release.outputs.released == 'true'
#        uses: mnao305/chrome-extension-upload@v5.0.0
#        with:
#          file-path: extension.zip
#          extension-id: ${{ vars.CHROME_EXTENSION_ID }}
#          client-id: ${{ vars.CHROME_CLIENT_ID }}
#          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
