name: Sync Selectors to Gist

on:
  push:
    branches:
      - main
    paths:
      - 'src/config/selectors.json'

jobs:
  sync_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET_TOKEN }}
          gist_id: ${{ vars.GIST_ID }}
          gist_file_name: selectors.json
          file_path: src/config/selectors.json
